const data = [{
  url: 'https://github.com/',
  img: '../image/github.ico',
  title: 'GitHub',
  desc: '一个面向开源及私有软件项目的托管平台',
  type: '［前端］代码托管',
},
{
  url: 'https://github.com/Mrlhz',
  img: '../image/favicon.ico',
  title: 'Mrlhz',
  desc: '我的github',
  type: '',
},
{
  url: 'https://mrlhz.github.io/blog',
  img: '../image/favicon.ico',
  title: '恋空一译',
  desc: 'My Blog',
  type: '',
},
{
  url: 'https://developer.mozilla.org/zh-CN/',
  img: '../image/mdn.png',
  title: 'MDN Web 文档',
  desc: '提供开放网络技术有关的信息',
  type: '',
},
{
  url: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript',
  img: '../image/mdn.png',
  title: 'JavaScript',
  desc: 'Web 开发技术JavaScript',
  type: '',
},
{
  url: 'https://leetcode-cn.com/',
  img: '../image/leetcode.ico',
  title: 'LeetCode',
  desc: '全球极客挚爱的技术成长平台',
  type: '',
},
{
  url: 'https://regexper.com/',
  img: '../image/regexper.ico',
  title: 'Regexper',
  desc: '正则表达式的可视化开源工具',
  type: '',
},
{
  url: 'https://yiyibooks.cn/',
  img: '../image/yiyibooks.ico',
  title: '一译',
  desc: '在线技术文档协作翻译网',
  type: '',
},
{
  url: 'http://nodejs.cn/',
  img: '../image/node.png',
  title: 'Node.js',
  desc: 'Node.js 中文网',
  type: '',
},
{
  url: 'https://www.html.cn/doc/jsdoc/index.html',
  img: '../image/jsdoc_html.ico',
  title: 'JSDoc',
  desc: 'JSDoc 在线学习参考手册文档',
  type: '',
},
{
  url: 'https://translate.google.cn/',
  img: '../image/translate.google.cn_favicon.ico',
  title: 'Google翻译',
  desc: 'Google 的免费翻译服务',
  type: '',
},
{
  url: 'https://fanyi.baidu.com/',
  img: '../image/fanyi.baidu.ico',
  title: '百度翻译',
  desc: '百度提供的翻译服务',
  type: '',
},
{
  url: 'https://www.npmjs.com/',
  img: '../image/npmjs.png',
  title: 'Npmjs',
  desc: 'JS管理包及强大的构建工具',
  type: '',
},
{
  url: 'http://codepen.io/',
  img: '../image/codepen.png',
  title: 'codepen',
  desc: '前端炫酷样式技能效果',
  type: '',
},
{
  url: 'https://www.runoob.com/',
  img: '../image/runoob.ico',
  title: '菜鸟教程',
  desc: '学的不仅是技术,更是梦想',
  type: '',
},
{
  url: 'https://docschina.org/',
  img: '../image/docschina.ico',
  title: '印记中文',
  desc: 'Web 前端开发人员提供优质文档',
  type: '',
},
{
  url: 'https://w3techs.com/',
  img: '../image/w3techs.ico',
  title: 'w3techs',
  desc: 'web网站技术调查报告',
  type: '',
},
{
  url: 'https://www.bilibili.com/',
  img: '../image/bilibili.ico',
  title: 'bilibili',
  desc: '国内领先的年轻人文化社区',
  type: '',
},
{
  url: 'https://stackoverflow.com/',
  img: '../image/stackoverflow.ico',
  title: 'Stackoverflow',
  desc: '全球专业的程序员IT技术问答社区',
  type: '',
},
{
  url: 'http://es6.ruanyifeng.com/',
  img: '../image/es6.ico',
  title: 'ECMAScript 6 入门',
  desc: '开源的 JavaScript 语言教程',
  type: '',
},
{
  url: 'https://www.runoob.com/jsref/jsref-obj-regexp.html',
  img: '../image/runoob.ico',
  title: 'JavaScript RegExp 对象',
  desc: 'JavaScript RegExp 对象',
  type: '',
},
{
  url: 'https://babeljs.io/repl',
  img: '../image/babel.png',
  title: 'babeljs',
  desc: '下一代 JavaScript 语法的编译器',
  type: '',
},
{
  url: 'https://developer.mozilla.org/zh-CN/docs/Web/CSS/Reference',
  img: '../image/mdn.png',
  title: 'CSS 参考',
  desc: 'CSS 参考页面以浏览按 字母索引',
  type: '',
},
{
  url: 'https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp',
  img: '../image/mdn.png',
  title: 'RegExp',
  desc: 'JavaScript 标准内置对象 - RegExp',
  type: '',
},
{
  url: 'http://eslint.cn/',
  img: '../image/eslint.png',
  title: 'ESLint',
  desc: '可组装的JavaScript和JSX检查工具',
  type: '',
},
{
  url: 'https://editorconfig.org/',
  img: '../image/EditorConfig.png',
  title: 'EditorConfig',
  desc: '为在不同编辑器和ide中处理同一项目的多个开发人员维护一致的编码样式',
  type: '',
},
{
  url: 'https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status',
  img: '../image/mdn.png',
  title: 'Status',
  desc: 'HTTP 响应代码',
  type: '',
},
{
  url: 'https://jestjs.io/docs/zh-Hans',
  img: '../image/jestjs.ico',
  title: 'jestjs',
  desc: 'Delightful JavaScript Testing',
  type: '',
},
{
  url: 'https://www.npmjs.cn/',
  img: '../image/npmjs.png',
  title: 'npm 中文文档',
  desc: 'npm 中文文档',
  type: '',
},
{
  url: 'https://cn.vuejs.org/v2/guide/index.html',
  img: '../image/vue-32x32.png',
  title: ' Vue.js',
  desc: '一套用于构建用户界面的渐进式框架',
  type: '',
},
{
  url: 'https://v3.cn.vuejs.org/guide/introduction.html',
  img: '../image/vue-32x32.png',
  title: 'Vue.js 3.0',
  desc: '一套用于构建用户界面的渐进式框架',
  type: '',
},
{
  url: 'https://vue-js.com/learn-vue/',
  img: '../image/vue-32x32.png',
  title: '逐行剖析 Vue.js 源码',
  desc: 'Vue源码系列-Vue中文社区',
  type: '',
},
{
  url: 'https://juejin.cn/',
  img: '../image/juejin_favicon-32x32.png',
  title: '掘金',
  desc: '掘金 - 代码不止，掘金不停',
  type: '',
},
]

export const list = data;

export const day = 1;
